In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
print(f'torch version: {torch.__version__}')

torch version: 2.9.1+cu126


# Introduction to Tensor

## 1. Creating Tensor

### Initializing & basic operations

#### A tensorr can be constructed form a Python list or sequence using the torch.tensor() constructor

In [ ]:
tensor1 = torch.tensor([[1., 1.], [1., 1.]])
tensor1

tensor([[1., 1.],
        [1., 1.]])

In [11]:
tensor2 = torch.tensor(np.array([[1, 2], [3, 4]]))
tensor2

tensor([[1, 2],
        [3, 4]])

__Note: torch.tensor(): always copy data__

#### A tensor of specific data type can be constructed by passing a torch.dtype and/or a torch.device to a constructor or tensor creation op:

In [13]:
tensor3 = torch.zeros((2, 4), dtype=torch.int32)
tensor3

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [14]:
cuda0 = torch.device('cuda:0')
tensor4 = torch.ones((2, 4), dtype=torch.float32, device=cuda0)
tensor4

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

#### The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation

In [20]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(x[0, 2])

x[0, 2] = 11
print(x)

# convert tensor to a standard python number --> using .item()
# apply for tensor with one element
y = torch.tensor([2.45])

print(f'y: {y} with type: {type(y)}')
print(f'python number: {y.item()} with type: {type(y.item())}')

tensor(3)
tensor([[ 1,  2, 11],
        [ 4,  5,  6]])
y: tensor([2.4500]) with type: <class 'torch.Tensor'>
python number: 2.450000047683716 with type: <class 'float'>
